### ISSUE TITLE
Bar shows under edge terminal

### ISSUE THREAD

**Issue by maganoegi** [pollev/python_progress_bar#1]
The bar is placed under the terminal, only a tiny portion is visible. I'm a Linux Mint Tina 19.2, and had no such issues with the bash version, built-int terminal with zsh (tested without as well)

Even when nothing is printed and we use an empty for loop, the cursor keeps pushing "down" with each iteration.

**Comment by pollev** [comment]
Can you try now? I cannot reproduce the issue but I made an educated guess to fix the problem

**Comment by maganoegi** [comment]
Oke, having tested it, the situation is the following:
It works fine AS LONG as something is printed on a given iteration. If not it just sits quiet, and then pops to 34% and then 70%. But if in every iteration something is printed, the behaviour is very nice.

Also, this is the same for different sleep() speeds.

**Comment by maganoegi** [comment]
this seems to fix it:
def __print_control_code(code):
    print(code, end='\r')

**Comment by pollev** [comment]
Thanks for the fix recommendation. It helped me figure out the root of the problem.
I fixed it with a slightly less impactful change. Feel free to try it out

**Comment by maganoegi** [comment]
Unfortunately it breaks! 

![broken](https://user-images.githubusercontent.com/35732634/74456582-56152800-4e87-11ea-9173-8ceccd87aec8.png)

**Comment by pollev** [comment]
Can you send me the full code that is failing (so i can replicate the issue).

I ask because you clearly modified some of it (red highlight)

**Comment by maganoegi** [comment]
Ok,  just make the same change as in the commit in my version - move the \r. I've played around with colors, moving elements, removed the 50% break, and wrote a name==main part. The rest is the same. Will send an email
