### ISSUE TITLE
Does not work with logging

### ISSUE THREAD

**Issue by MajorCarrot** [pollev/python_progress_bar#3]
The progress bar and logging compete to write on the screen causing something like this:

![error_output](https://user-images.githubusercontent.com/25938552/91040778-6e32e480-e62c-11ea-9039-18324b08a1fd.png)

It might be difficult to fix this though. Any ideas?

Note: I had modified your code to test with logging. The modified script is:

```
#!/usr/bin/env python3

import random
import string
import time
import logging

# Import the progress bar
from python_progress_bar import progress_bar
LOGGER = logging.getLogger(__name__)


def random_string(string_length=30):
    letters = string.ascii_lowercase
    return ''.join(random.choice(letters) for i in range(string_length))


def generate_some_output_and_sleep():
    LOGGER.error("Here is some output")
    LOGGER.error(random_string())
    LOGGER.error(random_string())
    LOGGER.error(random_string())
    LOGGER.error(random_string())
    LOGGER.error(
        "\n\n------------------------------------------------------------------"
    )
    LOGGER.error("\n\n Now sleeping briefly")
    time.sleep(0.3)


def main():
    # Make sure that the progress bar is cleaned up when user presses ctrl+c
    progress_bar.enable_trapping()
    # Create progress bar
    progress_bar.setup_scroll_area()
    for i in range(99):
        if i == 50:
            LOGGER.error("waiting for user input: ")
            progress_bar.block_progress_bar(i)
            input("User input: ")
        else:
            generate_some_output_and_sleep()
            progress_bar.draw_progress_bar(i)
    progress_bar.destroy_scroll_area()


main()
```

**Comment by MajorCarrot** [comment]
It seems to work great with print statements though!

**Comment by pollev** [comment]
Hi,

This is somewhat of a misuse of the progress bar or the logging framework. :)
You can fix this pretty easily by logging to stdout rather than to whatever the logging module in python logs to by default.

```
root = logging.getLogger()
handler = logging.StreamHandler(sys.stdout)
root.addHandler(handler)
LOGGER = logging.getLogger(__name__)
```

Adding this to your example script (and importing 'sys') fixes the problem for me.
Let me know if you encounter further issues.

**Comment by pollev** [comment]
Update: Although the solution I provided above might not be the cleanest way of doing this.
Refer to [this stackoverflow](https://stackoverflow.com/questions/14058453/making-python-loggers-output-all-messages-to-stdout-in-addition-to-log-file) for more information.

**Comment by MajorCarrot** [comment]
Thanks. Will try this out and let you know!
